<?php
/*
 * Created by Martin Wernståhl on 2011-04-23.
 * Copyright (c) 2011 Martin Wernståhl.
 * All rights reserved.
 */

namespace Inject\Stack\Middleware;

use \Inject\Stack\MiddlewareInterface;
use \Inject\Stack\Request;
use \Inject\Stack\Util;

/**
 * Renders a status message if a HTTP error status (>= 400) is passed without a body.
 */
class ShowStatus implements MiddlewareInterface
{
	/**
	 * The callback for the next middleware or the endpoint in this middleware
	 * stack.
	 * 
	 * @var \Inject\Stack\MiddlewareInterface|Closure|ObjectImplementing__invoke
	 */
	protected $next;
	
	// ------------------------------------------------------------------------
	
	/**
	 * Tells this middleware which middleware or endpoint it should call if it
	 * wants the call-chain to proceed.
	 * 
	 * @param  \Inject\Stack\MiddlewareInterface|Closure|ObjectImplementing__invoke
	 */
	public function setNext($next)
	{
		$this->next = $next;
	}
	
	// ------------------------------------------------------------------------
	
	/**
	 * Performs the operations of the middleware.
	 * 
	 * @param  array
	 * @return array(int, array(string => string), string)
	 */
	public function __invoke($env)
	{
		$callback = $this->next;
		$ret      = $callback($env);
		
		if(empty($ret[2]) && $ret[0] >= 400)
		{
			$rendered = $this->renderTemplate($ret[0], $env);
			
			$ret = array(
				$ret[0],
				array('Content-Type' => 'text/html', 'Content-Length' => strlen($rendered)),
				$rendered
			);
		}
		
		return $ret;
	}
	
	// ------------------------------------------------------------------------

	/**
	 * Renders the template for the status message.
	 * 
	 * @return string
	 */
	public function renderTemplate($response_code, $env)
	{
		$response_msg = Util::getHttpStatusText($response_code);
		
		$req = new Request($env);
		
		ob_start();
		?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title><?php echo $response_code.': '.$response_msg.' at '.$env['SCRIPT_NAME'].$env['PATH_INFO']; ?></title>
		<meta name="robots" content="NONE,NOARCHIVE" />
	</head>
	<body>
		<h1><span><?php echo $response_code; ?></span> <?php echo $response_msg; ?></h1>
		
		<h3>Request method</h3>
		
		<p><?php echo $env['REQUEST_METHOD']; ?></p>
		
		<h3>Request Url</h3>
		
		<p><code><?php echo $req->getRequestUrl(); ?></code></p>
		
		<p>
			Message generated by <code>\Inject\Stack\Middleware\ShowStatus</code> after receiving error code <code><?php echo $response_code; ?></code>.
		</p>
	</body>
</html>
		<?php
		
		return ob_get_clean();
	}
}


/* End of file ShowStatus.php */
/* Location: src/php/Inject/Stack/Middleware */